import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import {
  ClerkProvider,
  SignedIn,
  SignOutButton,
} from '@clerk/nextjs'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="w-full h-14  sticky top-0 z-10 flex items-center justify-between bg-gray-100 px-4">
            <h1 className="text-2xl font-bold">
              <Link href="/">PostWatcher</Link>
            </h1>
            <div className="flex gap-4">
              <SignedIn>
                <SignOutButton>
                  <button className="bg-pink-600 px-4 py-2 rounded-3xl text-white">
                    Sign Out
                  </button>
                </SignOutButton>
              </SignedIn>
            </div>
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
